language: java
sudo: true
jdk:
  - oraclejdk8
install:
  - sudo apt-get install -qq time
  - pip install --user jinja2
script:
  - make gradle maven ant_ivy buildr buck
notifications:
  email: false
branches:
  only:
    - master
    - develop
