language: java
sudo: false
jdk:
  - oraclejdk8
install:
  - pip install --user jinja2
# refresh caches, travis uploads after install
  - TERM=dumb make CONFIG=configs/generated_minimal.mk
script:
  - TERM=dumb make
  - TERM=dumb make -j2 clean
  - TERM=dumb make gradle2.9 maven3.3.9 ant_ivy1.9.6 buildr1.4.23 buckv2015.11.30.01 leiningen2.5.3 sbt0.13.9 pants0.0.63
  - TERM=dumb make CONFIG=configs/commons-math.mk
  - TERM=dumb make CONFIG=configs/generated_multi.mk
cache:
  directories:
  - caches
notifications:
  email: false
branches:
  only:
    - master
    - develop
