language: java
sudo: false
jdk:
  - oraclejdk8
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
install:
  - cd scripts/nodejs; npm install; cd ../..
  - cd scripts/nodejs; ./node_modules/.bin/mdast ../../*.md --frail --no-color -q --config-path ./mdast/mdastrc; cd $TRAVIS_BUILD_DIR

cache:
  directories:
  - $TRAVIS_BUILD_DIR/scripts/nodejs
  - $TRAVIS_BUILD_DIR/caches
  - $HOME/.cache/pip
  - $HOME/.m2
  - $HOME/.buildr
  - $HOME/.gradle
notifications:
  email: false
branches:
  only:
    - gh-pages
