language: java
sudo: true
jdk:
  - oraclejdk8
install:
  - sudo apt-get install -qq time
  - pip install --user jinja2
script:
  - TERM=dumb make
  - TERM=dumb make clean
  - TERM=dumb make gradle2.8 maven3.3.3 ant_ivy1.9.5 buildr1.4.22 buck2015.12.23.01 leiningen2.5.2 sbt0.13.8 pants0.0.45
  - TERM=dumb make CONFIG=commons-math.mk
  - TERM=dumb make versions
notifications:
  email: false
branches:
  only:
    - master
    - develop
