language: java
sudo: false
jdk:
  - oraclejdk8
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
install:
  - pip install -q --user jinja2
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  # bazel extra option for travis
  - echo -e "export BAZEL_COMMAND_OPTIONS:=--spawn_strategy=standalone --genrule_strategy=standalone" > custom.mk
# refresh caches, travis uploads after install
  - TERM=dumb make maven3.3.9 bazel0.2.3 CONFIG=configs/generated_minimal.mk
script:
  - TERM=dumb rm -rf build
  - TERM=dumb make maven3.3.9 bazel0.2.3 CONFIG=configs/generated_multi.mk
  - cat build/reports/multi-16-10.csv
cache:
  directories:
  - $TRAVIS_BUILD_DIR/scripts/nodejs
  - $TRAVIS_BUILD_DIR/caches
  - $HOME/.cache/pip
  - $HOME/.m2
  - $HOME/.buildr
  - $HOME/.gradle
notifications:
  email: false
branches:
  only:
    - master
    - develop
